name: Deploy Storybook

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest #define o ambiente para deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
      - run: npm ci --legacy-peer-deps #ci npm install para ambientes sem interação --legacy-peer-deps para storybook que foi criado com npm 7 e react 17

      - name:
      - run: npm run build-storybook #roda o script de construção do build do storybook

      - name: Deploy Storybook
      - run: npm run deploy-storybook -- --ci --existing-output-dir=storybook-static
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} #configurações do Github para acesso a branches etc...